### ISSUE TITLE
multi file installs

### ISSUE THREAD

**Issue by erikng** [1dustindavis/gorilla#64]
Unlike debian and macOS, it is likely that installers may require multiple files to chain together for installations.

Some examples:
- MSI with a transform file (.mst)
- MSI with a patch file (.msp)
- Exe with custom files (.xml, .txt etc)

Rather than scripting powershell scripts or using inter dependent packages in catalogs as "required items", it would make sense if Gorilla could handle multi file installations and then be able to pass arguments to them.

Our team might be able to send PRs for this, but I would like to discuss the specifics prior to working on anything.

**Comment by 1dustindavis** [comment]
I agree this will likely be useful, but there are probably lots of edge cases.

One way to do this might be to add support for multiple items under `installer` like this:
```yaml
FakeApp:
  display_name: Fake Application
  check:
    registry:
      name: Fake Applications
      version: 68.0.3440.106
  installer:
    - location: packages/fake/FakeApp-68.0.3440.106.msi
      hash: ce9c44417489d6c1f205422a4b9e8d5181d1ac24b6dcae3bd68ec315efdeb18b
      type: nupkg
    - location: packages/fake/FakeApp-68.0.3440.106.msp
      hash: 65bf42b15a05b13197e4dd6cdf181e39f30d47feb2cb6cc929db21cd634cd36f
      type: support
  version: 68.0.3440.106
```

We will need a way to reference these files from the `arguments`. Maybe assign an identifier that gorilla can fill in with the path later?
```yaml
    - location: packages/fake/FakeApp-68.0.3440.106.msi
      hash: ce9c44417489d6c1f205422a4b9e8d5181d1ac24b6dcae3bd68ec315efdeb18b
      type: nupkg
      arguments:
       - /L=1033
       - /p $fake-msp-id
    - location: packages/fake/FakeApp-68.0.3440.106.msp
      hash: 65bf42b15a05b13197e4dd6cdf181e39f30d47feb2cb6cc929db21cd634cd36f
      type: support
      identifier: fake-msp-id

```

To set expectations, I wouldn't want to include this in 1.0. I would push this to 1.1.
